sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false
    options:
        environment: '%kernel.environment%'
        send_default_pii: true
        release: '%env(GIT_REF)%'
    monolog:
        error_handler:
            enabled: true
            level: error
