twig:
    globals:
        bucket_name: '%bucket.name%'
        bucket_dns: '%bucket.dns%'
        cdn_dns: '%cdn.dns%'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bulma_0_layout.html.twig']