version: '3.8'
services:
  api:
    image: nginx:1.17
    volumes:
    - ./api:/app
    - ./api/.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8000:80
    links:
      - php

  php:
    image: eerison/myprofile:dev
    working_dir: /app
    env_file:
      - ./api/.docker/common.env
    volumes:
      - ./api:/app
    links:
      - db

  client:
    image: node
    working_dir: /app
    volumes:
      - ./api:/app
    depends_on:
      - php

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myprofile
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myprofile
    volumes:
      - ./api/.docker/database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
