presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"

controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
