presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"

controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

profile:
    resource: ../../src/Controller/Profile/
    type: annotation
    prefix: /profile/{_locale}
    name_prefix: profile_

admin:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /admin/{_locale}
    name_prefix: admin_