imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: sentry
        sentry:
            type: raven
            dsn: '%sentry_dsn%'
        applog:
            type: raven
            dsn: '%sentry_dsn%'
            level: debug
            channels: ['app']
        default:
            type: rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            max_files: 5
            level: debug
        console:
            type: console
            process_psr_3_messages: false

fos_user:
    registration:
        confirmation:
            enabled: true
