version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5
  codecov: codecov/codecov@1.0.2

executors:
  environment_configuration:
    docker:
      - image: eerison/myprofile:dev
        environment:
          APP_ENV: test
      - image: postgres
        environment:
          POSTGRES_USER: myprofile
          POSTGRES_PASSWORD: 123456
    working_directory: /app

jobs:
  composer:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - attach_workspace:
          at: /app
      - run: make init
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor

  webpack:
    executor: environment_configuration
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: ls -l
      - attach_workspace:
          at: /app
      - run: make yarn
      - run: ls -l
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - public
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - public

  lint:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - attach_workspace:
          at: /app
      - run: make lint_phpcs
      - run: make lint_twig
      - run: make lint_container

  test_functional:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - attach_workspace:
          at: /app
      - run: ls -l
      - run: make init
      - run: make test
      - codecov/upload:
          file: coverage.xml
          conf: .circleci/codecov.yaml
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - bin/.phpunit

  pr_deploy:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: Auth heroku
          command: ./.circleci/auth_heroku.sh $HEROKU_USERNAME $HEROKU_API_KEY
#      - attach_workspace:
#            at: /app
#      - restore_cache:
#          keys:
#            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
#            - v5-build
#      - run:
#          name: Create App
#          command: |
#            heroku create staging-myprofile-pr-400
#            exit 0
      - run:
          name: Step up heroku web
          command: |
            heroku container:login
            docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
            docker build --tag web --target build --file ./.docker/dockerfiles/Dockerfile .
            docker tag web registry.heroku.com/staging-myprofile-pr-400/web
            docker push registry.heroku.com/staging-myprofile-pr-400/web
#      - heroku/push-docker-image:
#          app-name: staging-myprofile-pr-400
#          recursive: true
      - heroku/release-docker-image:
          app-name: staging-myprofile-pr-400

workflows:
  version: 2.1
  build-and-test:
    jobs:
#      - composer
#      - webpack:
#          requires:
#            - composer
#      - lint:
#          requires:
#            - composer
#      - test_functional:
#          requires:
#            - webpack
#            - lint
      - pr_deploy
#          requires:
#            - test_functional
