version: 2.1

executors:
  environment_configuration:
    docker:
      - image: eerison/myprofile
        environment:
          APP_ENV: test
      - image: postgres
        environment:
          POSTGRES_USER: myprofile
          POSTGRES_PASSWORD: 123456
    working_directory: /app

jobs:
  composer:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - run: make init
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - vendor

  webpack:
    executor: environment_configuration
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
            - v1-webpack-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: /app
      - run: make yarn
      - save_cache:
          key: v1-webpack-{{ checksum "composer.lock" }}
          paths:
            - node_modules
            - public

  phpcs:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
      - attach_workspace:
          at: /app
      - run: make phpcs

  phpunit:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
            - v1-webpack-{{ checksum "yarn.lock" }}
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - attach_workspace:
          at: /app
      - run: make test
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - bin/.phpunit

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - composer
      - webpack:
          requires:
            - composer
      - phpcs:
          requires:
            - composer
      - phpunit:
          requires:
            - webpack
            - phpcs