version: 2.1

executors:
  build:
    docker:
      - image: eerison/myprofile
        environment:
          APP_ENV: test
      - image: postgres
        environment:
          POSTGRES_USER: myprofile
          POSTGRES_PASSWORD: 123456
    working_directory: /app

jobs:
  build-composer:
    executor: build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}-{{ checksum "phpunit.xml.dist" }}
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - run: make init
      - persist_to_workspace:
          root: ./
          paths:
            - vendor

  build-webpack:
    executor: build
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}-{{ checksum "phpunit.xml.dist" }}
      - attach_workspace:
          at: /app
      - run: pwd
      - run: ls -l
      - run: ls -l vendor
      - run: make yarn
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - public

  test:
    executor: build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}-{{ checksum "phpunit.xml.dist" }}
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - attach_workspace:
          at: /app
      - run: pwd
      - run: ls -l
      - run: make phpcs
      - run: make test
      - save_cache:
          key: v2-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}-{{ checksum "phpunit.xml.dist" }}
          paths:
            - vendor
            - node_modules
            - public
            - bin/.phpunit

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-composer
      - build-webpack:
          requires:
            - build-composer
      - test:
          requires:
            - build-webpack