version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3

executors:
  environment_configuration:
    docker:
      - image: eerison/myprofile
        environment:
          APP_ENV: test
      - image: postgres
        environment:
          POSTGRES_USER: myprofile
          POSTGRES_PASSWORD: 123456
    working_directory: /app

jobs:
  composer:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - attach_workspace:
          at: /app
      - run: make init
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor

  webpack:
    executor: environment_configuration
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: ls -l
      - attach_workspace:
          at: /app
      - run: make yarn
      - run: ls -l
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - public
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - public

  phpcs:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - attach_workspace:
          at: /app
      - run: make phpcs

  phpunit:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - attach_workspace:
          at: /app
      - run: ls -l
      - run: make test
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - bin/.phpunit

  pr_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
#      - attach_workspace:
#            at: /app
#      - restore_cache:
#          keys:
#            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
#            - v5-build
#      - run:
#          name: Create App
#          command: |
#            heroku create staging-myprofile-pr-400
#            exit 0
      - run:
          name: Auth heroku
          command: |
            ./.circleci/auth_heroku.sh $HEROKU_USERNAME $HEROKU_API_KEY
            heroku login
      - heroku/release-docker-image:
          app-name: staging-myprofile-pr-400
      - heroku/push-docker-image:
          app-name: staging-myprofile-pr-400

workflows:
  version: 2.1
  build-and-test:
    jobs:
#      - composer
#      - webpack:
#          requires:
#            - composer
#      - phpcs:
#          requires:
#            - composer
#      - phpunit:
#          requires:
#            - webpack
#            - phpcs
#      - heroku_pr_deploy:
#          requires:
#            - phpunit
      - pr_deploy
