version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  environment_configuration:
    docker:
      - image: eerison/myprofile:dev
        environment:
          APP_ENV: test
      - image: postgres
        environment:
          POSTGRES_USER: myprofile
          POSTGRES_PASSWORD: 123456
    working_directory: /app

jobs:
  composer:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - attach_workspace:
          at: /app
      - run: make init
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor

  webpack:
    executor: environment_configuration
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: ls -l
      - attach_workspace:
          at: /app
      - run: make yarn
      - run: ls -l
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - public
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - public

  phpcs:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - attach_workspace:
          at: /app
      - run: make phpcs

  test_functional:
    executor: environment_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
            - v5-build
      - run: echo 127.0.0.1 db | tee -a /etc/hosts
      - attach_workspace:
          at: /app
      - run: ls -l
      - run: make init
      - run: make test
      - codecov/upload:
          file: coverage.xml
          conf: .circleci/codecov.yaml
      - save_cache:
          key: v5-build-{{ checksum "composer.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - bin/.phpunit

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - composer
      - webpack:
          requires:
            - composer
      - phpcs:
          requires:
            - composer
      - test_functional:
          requires:
            - webpack
            - phpcs