name: CI/CD
on: [pull_request]

jobs:
  pr-deploy:
    name: Pull request deploy
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.10.9
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "staging-myprofile-pr-400" #Must be unique in Heroku
            heroku_email: "erison.sdn@gmail.com"
            usedocker: true